/*
    Knut's GFX-Lib for Watcom

    Main-header file

    Last updated: 28/7-97
*/

#include "standard.h"           // Standard definitions
#include "stdvga.h"             // Standard VGA low-level functions
//#include "modex.h"              // Mode-X 320x400x256 functions
#include "palette.h"            // VGA palette-functions
//#include "prmitive.h"           // Geometric primitives functions
//#include "cgfx.h"               // C++ based gfx-functions

