/****************************************************************************/
/*   TITLE              Hangul Library <HAN> 4.1                            */
/*   SUB-TITLE          header file - key definitions                       */
/*   FILENAME           hanio.h                                             */
/*   DATE & TIME        06/25/92 (THU) 07:40                                */
/*   PROGRAMMER         Lee Hyun-Ho (ID:easyride)                           */
/****************************************************************************/

/* ÑÂ¸wÇ¡Å¡—a £¹ ¯aÄ…Å¡—a */

#define  UP    			0x48
#define  DOWN  			0x50
#define  LEFT  			0x4b
#define  RIGHT 			0x4d
#define  HOME  			0x47
#define  PGUP  			0x49
#define  END   			0x4f
#define  PGDN  			0x51
#define  INS   			0x52     
#define  DEL   			0x53

#define  F1    			0x3b
#define  F2    			0x3c
#define  F3    			0x3d
#define  F4    			0x3e
#define  F5    			0x3f
#define  F6    			0x40
#define  F7    			0x41
#define  F8    			0x42
#define  F9    			0x43
#define  F10   			0x44

#define  CTRLHOME  		0x77
#define  CTRLEND   		0x75
#define  CTRLLEFT  		0x73
#define  CTRLRIGHT 		0x74
#define  CTRLPGUP  		0x84
#define  CTRLPGDN  		0x76
#define  CTRLF1    		0x5e
#define  CTRLF2    		0x5f
#define  CTRLF3    		0x60
#define  CTRLF4    		0x61
#define  CTRLF5    		0x62
#define  CTRLF6    		0x63
#define  CTRLF7    		0x64
#define  CTRLF8    		0x65
#define  CTRLF9    		0x66
#define  CTRLF0    		0x67

#define  ALT1			0x78
#define  ALT2			0x79
#define  ALT3			0x7a
#define  ALT4			0x7b
#define  ALT5			0x7c
#define  ALT6			0x7d
#define  ALT7			0x7e
#define  ALT8			0x7f
#define  ALT9			0x80
#define  ALT0			0x81

#define  ALTA      		0x1e
#define  ALTB      		0x30
#define  ALTC      		0x2e
#define  ALTD      		0x20
#define  ALTE      		0x12
#define  ALTF      		0x21
#define  ALTG      		0x22
#define  ALTH      		0x23
#define  ALTI      		0x17
#define  ALTJ      		0x24
#define  ALTK      		0x25
#define  ALTL      		0x26
#define  ALTM      		0x32
#define  ALTN      		0x31
#define  ALTO      		0x18
#define  ALTP      		0x19
#define  ALTQ      		0x10
#define  ALTR      		0x13
#define  ALTS      		0x1f
#define  ALTT      		0x14
#define  ALTU      		0x16
#define  ALTV      		0x2f
#define  ALTW      		0x11
#define  ALTX      		0x2d
#define  ALTY      		0x15
#define  ALTZ      		0x2c

#define  ESC   			0x01
#define  YES   			0x15
#define  NO    			0x31
#define  ENTER                  0x1c
#define  SPACE                  0x39

/* ´a¯aÇ¡Å¡—a */

#define  _ESC      		0x1b
#define  _BS       		0x08
#define  _TAB			0x09
#define  _ENTER                 0x0d
#define  _SPACE                 0x20
#define  _CTRLQ			0x11
#define  _CTRLT			0x14
#define  _CTRLY    		0x19

/* Ç¡¥¡—a Ïiœ‹a */

#define  RIGHT_SHIFT 	0x01
#define  LEFT_SHIFT  	0x02
#define  CTRL        	0x04
#define  ALT         	0x08
#define  SCRL_LOCK   	0x10
#define  NUM_LOCK    	0x20
#define  CAPS_LOCK   	0x40
#define  INS_MODE    	0x80
