// GLOBAL DEFINITIONS

#ifndef _RCGLOBAL_H
#define _RCGLOBAL_H

// GAMEPLAY /////////////////////////////////////////////////////////////////

#define	ZVALS	320

#define OVERCAMZ  7000.0
#define OVERCAMX	2885.0
#define OVERMAXZ	2250.0

#define DIFFUSE		1

#define CAMZ      	4485.0
#define CAMX  		4230.0
#define MAXZ		  3650.0

#define HSIZE1		110
#define HRAND1		30
#define HSKY1			16
#define HSIZE0		88
#define HSKY0     13
#define HSIZE2		240

#define SLAKK1		60

#define FOCAL     32767
#define ANGLES		8192
#define CAMANGLES 1
#define COORS     6

#define ACO				20

#define BEREGNPAL	0

// FIXED DEFINES ////////////////////////////////////////////////////////////

#define VIEW1PL		1
#define VIEW2PL		2
#define OVERVIEW	0

#define BLANK			0
#define BIL				1
#define OBJEKT		2
#define TEXTURE		3

#endif
