
 #define        ENTER           13
 #define        ESC             27
 #define        SPACE           32
 #define        UP              72
 #define        DOWN            80
 #define        LEFT            75
 #define        RIGHT           77
 #define	HOME        	71
 #define	END             79
 #define	PGUP		73
 #define	PGDW		81
 #define	DEL		83

 #define        F1              59
 #define        F2              60
 #define        F3              61
 #define        F4              62
 #define        F5              63
 #define        F6              64
 #define        F7              65
 #define        F8              66
 #define        F9              67
 #define        F10             68

 #define        INS             82
 #define        BACKSPACE        8
